### ISSUE TITLE
Clarify setup language for config.rb in readme

### ISSUE THREAD

**Issue by tomcardoso** [voxmedia/middleman-google_drive#1]
Currently, the usage is explained as 

```
activate :google_drive, load_sheets: {
  mysheet: google_spreadsheet_key
  # moresheet: another_key
}
```

whereas really `google_spreadsheet_key` should be a string from an old-style Google Doc, like those at [g.co/oldsheets](g.co/oldsheets). For a second I thought it took an integer, so maybe letting the activate line be a bit more flexible and do a `to_s` on the google_spreadsheet_key if people forget to wrap it in quotation marks?

**Comment by tomcardoso** [comment]
Might as well also add language explaining that you _must_ set an email and "PROJECT NAME" under the "Consent" page on the Google Developer Console.

**Comment by ryanmark** [comment]
OMG totally missed this. I'll add the `to_s` bit, but the library works with all google spreadsheets now, not just old style ones.
