### ISSUE TITLE
Example using ArchieML

### ISSUE THREAD

**Issue by chrisboden** [voxmedia/middleman-google_drive#6]
Hi, Awesome tool. I've got everything set up and used the verge50 to learn how the spreadsheet data worked but don't have equivalent example for how docs work - please could you provide a couple of pointers for how to get the content from a doc printed out in a partial.

**Comment by ryanmark** [comment]
We haven't used archieml yet, so the best I can do is in the readme: https://github.com/voxmedia/middleman-google_drive/blob/master/README.md#documents
